blueprint:
  name: KNX Virtual Device - Switch
  description: Virtual KNX Device that represant in simple binary entity
  domain: automation
  input:
    address:
      name: Address
      description: KNX group address for switching the entity on and off. DPT 1.001
    state_address:
      name: State Address
      description: KNX group address for exposing the switch state of the entity. DPT 1.001
    target_entity:
      name: Entity
      description: The entity to keep in sync.
      selector:
        entity:
          filter:
            domain:
              - light
              - switch
              - input_boolean
  source_url: https://github.com/clemens321/homeassistant-blueprints/blob/main/knx_virtual_switch.yaml
variables:
  address: !input address
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: event_knx_reloaded
  - platform: event
    event_type: automation_reloaded
  - platform: event
    event_type: knx_event
    event_data:
      destination: !input address
    id: knx_event
action:
  - if:
      - condition: trigger
        id: knx_event
    then:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.destination == address and trigger.event.data.data == 1 }}"
            sequence:
              - service: homeassistant.turn_on
                data:
                  entity_id: !input target_entity
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.destination == address and trigger.event.data.data == 0 }}"
            sequence:
              - service: homeassistant.turn_off
                data:
                  entity_id: !input target_entity
    else:
      - service: knx.event_register
        data:
          address: "{{ address }}"
      - service: knx.exposure_register
        data:
          address: !input state_address
          type: binary
          entity_id: !input target_entity
